spring:
  profiles:
    active: "local"
  cloud:
    stream:
      bindings:
        domainEvents-out-0:
          destination: event.stats.validated
      rabbit:
        bindings:
          domainEvents-out-0:
            producer:
              routing-key-expression: '''event.stats.validated'''
    function:
      definition: domainEvents

aws:
  region: "us-east-1"
  dynamodb:
    endpoint: "http://localhost:8000"

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: event.stats.validated



management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
