server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: "ms-muebles-sas"
  cloud:
    stream:
      bindings:
        domainEvents-out-0:
          destination: event.stats.validated
      rabbit:
        bindings:
          domainEvents-out-0:
            producer:
              routing-key-expression: '''event.stats.validated'''
    function:
      definition: domainEvents
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
  profiles:
    active: "prod"

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:https://dynamodb.us-east-1.amazonaws.com}

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT:5671}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  queue: ${RABBITMQ_QUEUE:event.stats.validated}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
